title: "witt-devlog"
tagline: "witt-devlog"
description: "witt-devlog"
github_username: wittlevit
baseurl: "/"
url: "https://wittlevit.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

remote_theme: "tareqdandachi/jekyll-shell-theme"

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
